name: frontend-shared package
on: [push]
  # release:
    # types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install
      working-directory: frontend-shared
      run: npm install
    - name: Publish
      working-directory: frontend-shared
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}